esphome:
  name: solar-planter
  platform: ESP32
  board: esp32_c3

esp32:
  variant: ESP32C3
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

web_server:
  port: 80

ota:

deep_sleep:
  run_duration: 10s
  sleep_duration: 60min

sensor:
  - platform: adc
    pin: GPIO3
    name: "Soil Moisture Voltage"
    unit_of_measurement: "V"
  - platform: adc
    pin: GPIO5
    name: "LiPo Voltage"
    unit_of_measurement: "V"

binary_sensor:
  - platform: gpio
    pin: GPIO4
    name: "PIR Sensor"
    lambda: return esp_sleep_get_wakeup_cause();
    device_class: motion

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO10
    num_leds: 30
    chipset: ws2812
    name: "Status Light"
